### ISSUE TITLE
Async + classes?

### ISSUE THREAD

**Issue by Mrmagicpie** [GrpeApple/Overengineered-Hello-World#1]
i feel like to make this even more complicated you should add some classes and make it async, just a thought lmao

**Comment by Mrmagicpie** [comment]
just realized there are classes but either way

**Comment by GrpeApple** [comment]
can I close this?

**Comment by GrpeApple** [comment]
Hi, I suck at asyncio (or whatever)
but I decided to try anyway: 6aa4f97faefcff7564932ad7d16b1a6f9bd25ec9

**Comment by Mrmagicpie** [comment]
Very epic!

**Comment by GrpeApple** [comment]
I have now merged it into <code>master</code>, and I finally fiinished it.

**Comment by Mrmagicpie** [comment]
i forgot about this but it looks great 😂
